package universe.enums;

public enum PlanetaryFeature {
    PLANET_WIDE_CITY,
    UNDERGROUND_RIVER,
    LAGOON,
    SAND_DESERT,
    ROCK_DESERT,
    ROCKS,
    DUST,
    MESA,
    CANYON,
    MIXED_FOREST,
    BADLANDS,
    SEDIMENTARY_ROCKS,
    CLAY_RICH_SOIL,
    SHRUBS,
    HARDY_GRASS,
    RAVINE,
    PINNACLE,
    DEEP_COLD_OCEAN,
    BEACH,
    LICHEN,
    SUCCULENT,
    SHALLOW_WATER,
    MINERAL_WATER,
    CORAL_FOREST,
    OASIS,
    DUNES,
    MOUNTAIN_SPRING,
    SEA,
    HUGE_MOUNTAINS,
    KANYON,
    PLATEAU,
    SNOW_FOREST,
    LONG_RIVER,
    RIVER,
    RIVERBED,
    STEPPES,
    PRAIRIE,
    LOWLANDS,
    VALLEY,
    VULCANO,
    LAKE,
    LAVA_LAKE,
    LAVA_RIVER,

    /**
     * <h3>Unikátní pro slanou planetu</h3>
     * @see universe.celestial_body.planets.terran.habitable.dry.Salt Slaná planeta
     */
    SALT_FLAT,
    LARGE_CRYSTAL,
    SMALL_CRYSTAL,
    ARID_PLANES,
    SUBTERRANEAL_OCEAN,
    HILL,
    OCEAN,
    FLAT,

}
